# Generated by Django 2.2.4 on 2019-08-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_loop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='next_stop',
            field=models.OneToOneField(null='true', on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_stop', to='dragon_loop.Stop'),
            preserve_default='true',
        ),
        migrations.CreateModel(
            name='Transponder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transponders', to='dragon_loop.Bus')),
            ],
        ),
    ]
